.TH "updatecsv" "1" 

.SH Name
.PP
updatecsv - transfer data from one CSV file to another

.SH Synopsis
.PP
updatecsv [-h] [-s SEPARATOR] [-d] [--by ID_COLNAME] old_data input_data

.SH Description
.PP

This is a simple command-line tool for transferring data from one CSV file to another. This is done based on a specified column, which must contain unique identifiers (e.g., ID numbers). It's like a merge, but with a few constraints.

The program was designed for updating data frames with experiments data, where each row represents an experimental unit. Thus, it does not add new rows, and the identifiers in the input file must be a subset of those in the original file. Also, data from the original file cannot be overwritten.

The program creates a backup file, updates the original file, and prints the changes in the terminal.

.SH Options
.PP
-s    Specify the item separator in the csv files (default is comma)

.PP
-d    Dry-run with no changes made

.PP
--by  Defines the column to use for the merge (default is id)

.SH Examples

.PP
Adding new data with default values (comma as separator, id as merge column):

.B
updatecsv experiment_2023.csv aboveground_biomass.csv

.PP
Adding new data with custom options (semicolon as the separator, dry-run mode, and a custom merge column named 'key'):

.B
updatecsv -s ';' -d --by key experiment_2022.csv alkaloids.csv


.SH "Author"
.PP
Facundo Decunta 
