.TH "updatecsv" "1" 

.SH "Name"
.PP
updatecsv - update a csv with another csv

.SH "Synopsis"
.PP
updatecsv [-h] [-s SEPARATOR] [-d] [--by ID_COLNAME] old_data input_data

.SH "Description"
.PP

The command adds data from an input file to an existing DataFrame based on a specified ID column. If a column from the input file does not already exist in the DataFrame, it creates a new column. If the column already exists, it updates the data. The program does not overwrite existing data or introduce new IDs. It only accepts input files in CSV format.

.SS "Opciones"
.PP
-s    Specify the item separator in the csv files (default is comma)

.PP
-d    Dry-run with no changes made

.PP
--by  Defines the column to use for the merge (default is id)

.SH "Examples"

.PP
updatecsv experiment_data.csv plant_biomass.csv

Agrega los datos de plant_biomass.csv a la base de datos experiment_data.csv

.SH "Author"
.PP
fd 
